### ISSUE TITLE
Problem installing SCS in Matlab

### ISSUE THREAD

**Issue by JulioLop** [cvxgrp/scs#69]
Hello,

Actually, I use CVX 3.0, and  I want to install SCS on Matlab for working with it. But, it appears the following error: Can you help me?

With best regards

>>make_scs
 
Warning: MEX could not find the library "mwlapack"  
         specified with -l option on the path specified  
         with the -L option. 
   Creating library C:\USERS\JULIO\APPDATA\LOCAL\TEMP\MEX_FF~1\templib.x and object C:\USERS\JULIO\APPDATA\LOCAL\TEMP\MEX_FF~1\templib.exp 
cones.obj : error LNK2019: unresolved external symbol dsyevr referenced in function setUpSdConeWorkSpace 
cones.obj : error LNK2019: unresolved external symbol dsyr referenced in function projSemiDefiniteCone 
cones.obj : error LNK2019: unresolved external symbol dnrm2 referenced in function projSemiDefiniteCone 
cones.obj : error LNK2019: unresolved external symbol dscal referenced in function projSemiDefiniteCone 
ctrlc.obj : error LNK2019: unresolved external symbol utSetInterruptEnabled referenced in function startInterruptListener 
ctrlc.obj : error LNK2019: unresolved external symbol utIsInterruptPending referenced in function isInterrupted 
scs_direct.mexw64 : fatal error LNK1120: 6 unresolved externals 
 
  C:\PROGRA~1\MATLAB\R2009A\BIN\MEX.PL: Error: Link of 'scs_direct.mexw64' failed. 
 
??? Error using ==> mex at 218
Unable to complete successfully.

Error in ==> compile_direct at 17
eval(cmd);

Error in ==> make_scs at 44
compile_direct(flags, common_scs);

**Comment by bodono** [comment]
What version of windows are you using and what version of Matlab? It's a strange error because mwlapack is Matlab's built in lapack library.

At a Matlab prompt can you run the command:

libpath = fullfile(matlabroot,'extern','lib',computer('arch'),'microsoft')

And then make sure that the directory exists at that path. Then change make_scs line 8 from `flags.BLASLIB = '-lmwblas -lmwlapack';` to
```
flags.BLASLIB = sprintf('-L%s -lmwblas -lmwlapack', libpath);
```
and try running `make_scs` again. Let me know if that fixes it.

**Comment by JulioLop** [comment]
Thank you for the response.

I working with Windows 10 and Matlab 7.8 (R2009a). The directory no exist at the path. Thus, I follow the sugerence and obtain the following error:

 C:\PROGRA~1\MATLAB\R2009A\BIN\MEX.PL: Error: 'Files\MATLAB\R2009a\extern\lib\win64\microsoft' not found. 
 
??? Error using ==> mex at 218
Unable to complete successfully.

Error in ==> compile_direct at 17
eval(cmd);

Error in ==> make_scs at 45
compile_direct(flags, common_scs);

**Comment by bodono** [comment]
It looks like the matlabroot is pointing to the wrong place. Somewhere in the MATLAB directory there should be a file called `libmwlapack`, with some extension like `.lib` or `.dylib`, can you find that file?

**Comment by JulioLop** [comment]
Yes, I find this file with extension **.lib**  :
C:\Program Files\MATLAB\R2009a\extern\lib\win64\microsoft

Recently, I installed  SCS in a IMAC of my friend (with Matlab 2014a), but in my notebook I cannot.

**Comment by bodono** [comment]
Ok, then try changing make_scs.m line 8 from to
```
flags.BLASLIB = ' ''-LC:\Program Files\MATLAB\R2009a\extern\lib\win64\microsoft'' -lmwblas -lmwlapack';
```
(All the ' are single quotes, even the '').

**Comment by JulioLop** [comment]
Thank very much. Now, I could install SCS solver, but also I had to make the following change

`flags.link = '-lut';`  
to
`flags.link = ' ''-LC:\Program Files\MATLAB\R2009a\extern\lib\win64\microsoft'' -lut';`

Thank again. 
Julio
