### PR TITLE
CI: build against minimal CUDA redistributables, covering #322

### PR DESCRIPTION
**Pull request by tschm**
Refs #322.

## What #322 actually is

SCS compiles `linsys/gpu/*.c` with `$(CC)` rather than `nvcc` (`Makefile:236-240`), so those sources include the CUDA headers directly and `driver_types.h` pulls in `crt/host_defines.h`. Up to CUDA 12 the `crt/` headers shipped inside `cuda_nvcc`; **CUDA 13 split them into a separate `cuda_crt` redistributable**, confirmed against NVIDIA's manifests:

| | `cuda_nvcc` ships `include/crt/` | `cuda_crt` exists |
|---|---|---|
| 12.6.20 | yes | no |
| 13.0.48 | **no** | **yes** |

Hence the reported failure in a component-wise install:

```
driver_types.h:59:30: fatal error: crt/host_defines.h: No such file or directory
```

## Why the existing GPU job cannot catch it

It already builds with CUDA 13.2 — that is `Jimver/cuda-toolkit`'s current default — and is green, because the apt metapackage pulls `cuda-crt-*` in transitively. A CUDA-version matrix leg would add a passing job and no signal. The bug only exists for installs that pick individual components, which is how downstream packagers build.

## The test

New `cuda-redist` job assembling CUDA from the redistributable tarballs the way a packager does, over `12.6.0` and `13.0.0` — both sides of the split. The crt provider is resolved per version (`cuda_crt` on 13.x, falling back to `cuda_nvcc` on 12.x), and the job asserts `crt/host_defines.h` is present before building, so a future reshuffle fails here with a pointed message rather than as a compiler error downstream. Then `make gpu` and `make test_gpu`. Running the binary needs a device, so this is build-only — which is all #322 was about.

Writing it turned up a **second** missing component: `make gpu` then failed with

```
cuda_fp16.h:4492:10: fatal error: nv/target: No such file or directory
```

`<nv/target>` comes from `cuda_cccl`, which a runtime-only install also does not pull in. So the full header closure for host-compiled GPU sources is `cuda_cudart`, `cuda_cccl`, the crt provider, `libcublas`, `libcusparse` (plus `libnvjitlink`, which `libcusparse.so` records as a dependency for the linker to resolve).

Both legs pass, in 1m34s and 2m7s — cheaper than the existing `linux` job, since the tarballs stream straight through `tar` and are never stored.

Also documents the requirement next to `make gpu` in `docs/src/install/c.rst`, since a full-toolkit install hides it.

For the packaging question in #322: the CUDA 13 build works, it just needs `cuda_crt` and `cuda_cccl` added to the component list.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by bodono** [comment]
Thanks, this is a nice way to test the packager's view of CUDA rather than the metapackage's, and the two-component diagnosis on #322 was exactly right. Merging.
